apiVersion: apps/v1
kind: Deployment
metadata:
  name: akaunting
  namespace: akaunting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: akaunting
  template:
    metadata:
      labels:
        app: akaunting
    spec:
      containers:
      - name: akaunting
        image: 147997152282.dkr.ecr.us-east-1.amazonaws.com/akaunting:latest
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: akaunting-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: akaunting-config
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: akaunting-config
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: akaunting-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: DB_PREFIX
          valueFrom:
            configMapKeyRef:
              name: akaunting-config
              key: DB_PREFIX
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
