apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: akaunting
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_PASSWORD: akauntingpass
  MYSQL_DATABASE: akaunting
