apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-api
  namespace: akaunting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-api
  template:
    metadata:
      labels:
        app: php-api
    spec:
      containers:
        - name: php-api
          image: php-api:latest
          ports:
            - containerPort: 80
          env:
            - name: PHP_INI_SCAN_DIR
              value: /usr/local/etc/php/conf.d
